### ISSUE TITLE
Possibility to setup default repository for looking Jenkinsfile

### ISSUE THREAD

**Issue by eshepelyuk** [vaimr/pipeline-multibranch-defaults-plugin#1]
Hello

Is it possible to add another source of default `Jenkinsfile` to be retrieved from one of the source repositories.

The purpose of this us to avoid Jenkins administration as much as possible and rely on source repositories, i.e, implement CI-as-code.

**Comment by vaimr** [comment]
Yes, you can. I see it through the default setting from Jenkinsfile in scm,
but failed to do once I stopped trying, because this was not an objective.
It should be written in the plan :)

С уважением, Денис Сапоненко

2016-11-23 11:03 GMT+03:00 Evgeny Shepelyuk notifications@github.com:

**Comment by eshepelyuk** [comment]
Excuse me, I didn't understand your reply.

What I wanted - is it possible to implement plugin option to retrieve `default Jenkinsfile` from GIT repository and not from `global Jenkins script store`

**Comment by vaimr** [comment]
That's right. It is necessary to add one more point, the choice of which,
the setting will be receiving from the SCM

​

С уважением, Денис Сапоненко

2016-11-23 11:27 GMT+03:00 Evgeny Shepelyuk notifications@github.com:

**Comment by eshepelyuk** [comment]
So, this feature probably may be implemented in some of the new release ?

**Comment by vaimr** [comment]
Yes

С уважением, Денис Сапоненко

2016-11-23 11:59 GMT+03:00 Evgeny Shepelyuk notifications@github.com:
